name: offWhiteCottage
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6080412152223289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#7294d3'
    - '#8dd29b'
    - '#111727'
    - '#881816'
  brandStrength: 0.5
  lightness: 0.9137021333444864
  saturation: 0.2109305013436824
  rhythmicContrast: 0.17939558159559965
purpose: []
